# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'venSalir.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class ui_ven_salir(object):
    def setupUi(self, ven_salir):
        ven_salir.setObjectName("ven_salir")
        ven_salir.resize(293, 101)
        ven_salir.setModal(True)
        self.btnbox_salir = QtWidgets.QDialogButtonBox(ven_salir)
        self.btnbox_salir.setGeometry(QtCore.QRect(110, 50, 161, 32))
        self.btnbox_salir.setOrientation(QtCore.Qt.Horizontal)
        self.btnbox_salir.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.btnbox_salir.setObjectName("btnbox_salir")
        self.lbl_presalir = QtWidgets.QLabel(ven_salir)
        self.lbl_presalir.setGeometry(QtCore.QRect(110, 10, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_presalir.setFont(font)
        self.lbl_presalir.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_presalir.setObjectName("lbl_presalir")
        self.lbl_iwarn = QtWidgets.QLabel(ven_salir)
        self.lbl_iwarn.setGeometry(QtCore.QRect(30, 20, 61, 61))
        self.lbl_iwarn.setMinimumSize(QtCore.QSize(51, 0))
        self.lbl_iwarn.setText("")
        self.lbl_iwarn.setPixmap(QtGui.QPixmap(":/avisosalir/img/iconoaviso.png"))
        self.lbl_iwarn.setScaledContents(True)
        self.lbl_iwarn.setObjectName("lbl_iwarn")

        self.retranslateUi(ven_salir)
        self.btnbox_salir.accepted.connect(ven_salir.accept)
        self.btnbox_salir.rejected.connect(ven_salir.reject)
        QtCore.QMetaObject.connectSlotsByName(ven_salir)

    def retranslateUi(self, ven_salir):
        _translate = QtCore.QCoreApplication.translate
        ven_salir.setWindowTitle(_translate("ven_salir", "Quiere salir?"))
        self.lbl_presalir.setText(_translate("ven_salir", "Seguro que quiere salir?"))
import avisosalir_rc
