# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'venAcercaDe.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ven_acercade(object):
    def setupUi(self, ven_acercade):
        ven_acercade.setObjectName("ven_acercade")
        ven_acercade.setWindowModality(QtCore.Qt.NonModal)
        ven_acercade.resize(289, 103)
        ven_acercade.setModal(False)
        self.btn_ok = QtWidgets.QPushButton(ven_acercade)
        self.btn_ok.setGeometry(QtCore.QRect(150, 70, 75, 23))
        self.btn_ok.setObjectName("btn_ok")
        self.lbl_mensaje = QtWidgets.QLabel(ven_acercade)
        self.lbl_mensaje.setGeometry(QtCore.QRect(110, 20, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_mensaje.setFont(font)
        self.lbl_mensaje.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_mensaje.setObjectName("lbl_mensaje")
        self.lbl_icono = QtWidgets.QLabel(ven_acercade)
        self.lbl_icono.setGeometry(QtCore.QRect(30, 20, 61, 61))
        self.lbl_icono.setMinimumSize(QtCore.QSize(51, 0))
        self.lbl_icono.setText("")
        self.lbl_icono.setPixmap(QtGui.QPixmap(":/icono/img/logo.jpg"))
        self.lbl_icono.setScaledContents(True)
        self.lbl_icono.setObjectName("lbl_icono")
        self.lbl_minombre = QtWidgets.QLabel(ven_acercade)
        self.lbl_minombre.setGeometry(QtCore.QRect(110, 40, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_minombre.setFont(font)
        self.lbl_minombre.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_minombre.setObjectName("lbl_minombre")

        self.retranslateUi(ven_acercade)
        QtCore.QMetaObject.connectSlotsByName(ven_acercade)

    def retranslateUi(self, ven_acercade):
        _translate = QtCore.QCoreApplication.translate
        ven_acercade.setWindowTitle(_translate("ven_acercade", "Acerca de"))
        self.btn_ok.setText(_translate("ven_acercade", "OK"))
        self.lbl_mensaje.setText(_translate("ven_acercade", "Version 0.0.1"))
        self.lbl_minombre.setText(_translate("ven_acercade", "Santiago Barreiro Chapela"))
