# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'venConfirmacion.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ven_confirmacion(object):
    def setupUi(self, ven_confirmacion):
        ven_confirmacion.setObjectName("ven_confirmacion")
        ven_confirmacion.setWindowModality(QtCore.Qt.ApplicationModal)
        ven_confirmacion.resize(350, 98)
        ven_confirmacion.setModal(True)
        self.btnbox_confirmar = QtWidgets.QDialogButtonBox(ven_confirmacion)
        self.btnbox_confirmar.setGeometry(QtCore.QRect(140, 50, 161, 32))
        self.btnbox_confirmar.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.btnbox_confirmar.setOrientation(QtCore.Qt.Horizontal)
        self.btnbox_confirmar.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.btnbox_confirmar.setObjectName("btnbox_confirmar")
        self.lbl_pregunta = QtWidgets.QLabel(ven_confirmacion)
        self.lbl_pregunta.setGeometry(QtCore.QRect(100, 10, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_pregunta.setFont(font)
        self.lbl_pregunta.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_pregunta.setObjectName("lbl_pregunta")
        self.lbl_iwarn = QtWidgets.QLabel(ven_confirmacion)
        self.lbl_iwarn.setGeometry(QtCore.QRect(30, 20, 61, 61))
        self.lbl_iwarn.setMinimumSize(QtCore.QSize(51, 0))
        self.lbl_iwarn.setText("")
        self.lbl_iwarn.setPixmap(QtGui.QPixmap(":/avisosalir/img/iconoaviso.png"))
        self.lbl_iwarn.setScaledContents(True)
        self.lbl_iwarn.setObjectName("lbl_iwarn")

        self.retranslateUi(ven_confirmacion)
        self.btnbox_confirmar.accepted.connect(ven_confirmacion.accept)
        self.btnbox_confirmar.rejected.connect(ven_confirmacion.reject)
        QtCore.QMetaObject.connectSlotsByName(ven_confirmacion)

    def retranslateUi(self, ven_confirmacion):
        _translate = QtCore.QCoreApplication.translate
        ven_confirmacion.setWindowTitle(_translate("ven_confirmacion", "Está seguro/a?"))
        self.lbl_pregunta.setText(_translate("ven_confirmacion", "Está seguro/a?"))
