# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'venCalendar.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class ui_ven_calendar(object):
    def setupUi(self, ven_calendar):
        ven_calendar.setObjectName("ven_calendar")
        ven_calendar.resize(407, 305)
        self.calendar = QtWidgets.QCalendarWidget(ven_calendar)
        self.calendar.setGeometry(QtCore.QRect(0, 0, 401, 301))
        self.calendar.setObjectName("calendar")

        self.retranslateUi(ven_calendar)
        QtCore.QMetaObject.connectSlotsByName(ven_calendar)

    def retranslateUi(self, ven_calendar):
        _translate = QtCore.QCoreApplication.translate
        ven_calendar.setWindowTitle(_translate("ven_calendar", "Fecha Alta"))
